backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
#  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
#    label: "Post" # Used in the UI, ie.: "New Post"
#    folder: "site/content/post" # The path to the folder where the documents are stored
#    create: true # Allow users to create new documents in this collection
#    fields: # The fields each document in this collection have
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Intro Blurb", name: "description", widget: "text"}
#      - {label: "Image", name: "image", widget: "image", required: false}
#      - {label: "Body", name: "body", widget: "markdown"}

  - name: "sponsor" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sponsors" # Used in the UI, ie.: "New Post"
    folder: "site/content/sponsor" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "title", widget: "string"}
      - {label: "link", name: "link", widget: "string"}
      - {label: "Order", name: "ord", widget: "number", default: 0, valueType: "int"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Type", name: "type", widget: "hidden", default: "sponsor"}
  - name: "speaker" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Speakers" # Used in the UI, ie.: "New Post"
    folder: "site/content/speaker" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "speaker"}
  - name: "feature" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Features" # Used in the UI, ie.: "New Post"
    folder: "site/content/feature" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Order", name: "ord", widget: "number", default: 0, valueType: "int"}
      - {label: "Type", name: "type", widget: "hidden", default: "feature"}
  - name: "homesections" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Home Sections" # Used in the UI, ie.: "New Post"
    folder: "site/content/homesections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Order", name: "ord", widget: "number", default: 0, valueType: "int"}
      - {label: "Type", name: "type", widget: "hidden", default: "home"}
  - name: "programmain" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Programs Main Hall" # Used in the UI, ie.: "New Post"
    folder: "site/content/programs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "string", required: false}
      - {label: "Start Time", name: "startTime", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "programmain"}

      
  - name: "workshop" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Workshops A" # Used in the UI, ie.: "New Post"
    folder: "site/content/workshop" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "string", required: false}
      - {label: "Start Time", name: "startTime", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "workshop"}
  - name: "workshop2" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Workshops B" # Used in the UI, ie.: "New Post"
    folder: "site/content/workshop2" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "string", required: false}
      - {label: "Start Time", name: "startTime", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "workshop2"}
  - name: "workshop3" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Prayer Hall" # Used in the UI, ie.: "New Post"
    folder: "site/content/workshop3" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "string", required: false}
      - {label: "Start Time", name: "startTime", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "workshop3"}
  - name: "workshop4" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Expert Studio" # Used in the UI, ie.: "New Post"
    folder: "site/content/workshop4" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Speaker", name: "speaker", widget: "string", required: false}
      - {label: "Start Time", name: "startTime", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "workshop4"}
  - name: "bus" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Bus" # Used in the UI, ie.: "New Post"
    folder: "site/content/transportation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "bus"}
  - name: "faq" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Faq" # Used in the UI, ie.: "New Post"
    folder: "site/content/qa" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "qa"}
  - name: "gallery" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Gallery" # Used in the UI, ie.: "New Post"
    folder: "site/content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "body", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "gallery"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Email Link, name: email, widget: string}
          - {label: Ticket Link, name: ticket, widget: string}
          
          
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
